{
 "title": "Elasticsearch Nginx Logs",
 "description": "Browse, analyze logs in Elasticsearchstatus_codes, pie-chart, top 10 clientip, line-chart,word-map and etc...",
 "tags": [
  "nginx",
  "es",
  "logstash",
  "log"
 ],
 "time": { "from": "now/w", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain name",
    "query": "{\"find\":\"terms\",\"field\":\"domain.keyword\"}"
   },
   { "name": "responsetime", "label": "Responce time", "query": "1,2,3,4,5,10" },
   {
    "name": "inter",
    "label": "Inter",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host name",
    "query": "{\"find\":\"terms\",\"field\":\"host.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "4** statuses (by domain)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "request.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "status:[400 TO 499] AND domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total HTTP status code 404",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "domain.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status:\"404\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain HTTP status code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain request method ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_method.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total 404 errors by all domains",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "domain.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status:\"404\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain request top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain user_agent top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_user_agent.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain number of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain HTTP status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none", "label": "Number of status codes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}